apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app.kubernetes.io/name: {{ include "citizen.name" . }}
    helm.sh/chart: {{ include "citizen.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ tpl (.Files.Glob "files/*").AsConfig . | indent 2 }}
