{{ if .Values.app_envs.CITIZEN_STORAGE_BUCKET }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "citizen.fullname" . }}-gcp-key
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "secrets/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
{{ end }}
